version: "3.7"

services:
  mongodb:
    image: mongo:bionic
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file: .env
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./database:/data/db
